package com.mobile.scrcpy.android.infrastructure.adb.usb

import dadb.AdbKeyPair
import java.io.IOException

/**
 * USB ADB 认证工具
 */
internal object UsbAdbAuth {
    /**
     * 使用 RSA 私钥签名 token
     * 参考 dadb 的实现
     */
    @OptIn(ExperimentalUnsignedTypes::class)
    fun signToken(
        token: ByteArray,
        keyPair: AdbKeyPair,
    ): ByteArray {
        try {
            // 获取私钥（使用反射）
            val privateKeyField = keyPair.javaClass.getDeclaredField("privateKey")
            privateKeyField.isAccessible = true
            val privateKey = privateKeyField.get(keyPair) as java.security.PrivateKey

            // RSA 签名
            val cipher = javax.crypto.Cipher.getInstance("RSA/ECB/NoPadding")
            cipher.init(javax.crypto.Cipher.ENCRYPT_MODE, privateKey)

            // 添加签名填充
            val signaturePadding =
                ubyteArrayOf(
                    0x00u,
                    0x01u,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0xffu,
                    0x00u,
                    0x30u,
                    0x21u,
                    0x30u,
                    0x09u,
                    0x06u,
                    0x05u,
                    0x2bu,
                    0x0eu,
                    0x03u,
                    0x02u,
                    0x1au,
                    0x05u,
                    0x00u,
                    0x04u,
                    0x14u,
                ).toByteArray()

            cipher.update(signaturePadding)
            return cipher.doFinal(token)
        } catch (e: Exception) {
            throw IOException("Failed to sign token: ${e.message}", e)
        }
    }

    /**
     * 获取公钥字节数组
     */
    fun getPublicKeyBytes(keyPair: AdbKeyPair): ByteArray {
        val publicKeyBytesField = keyPair.javaClass.getDeclaredField("publicKeyBytes")
        publicKeyBytesField.isAccessible = true
        return publicKeyBytesField.get(keyPair) as ByteArray
    }
}
